import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[600px] min-h-screen m-auto px-[15px] bg-white shadow-[0px_7px_29px_0px_rgba(100,_100,_111,_0.2)]">
          <header className="h-[60px] leading-[60px] font-bold text-[18px]">
            <Link href={"/"}>📚 ONEBITE BOOKS</Link>
          </header>
          <main className="pt-[10px]">{children}</main>
          <footer className="py-[100px] text-gray-500">제작 @choiboram</footer>
        </div>
      </body>
    </html>
  );
}
