import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { BookData } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,
    { cache: "force-cache" }
  );
  if (!response.ok)
    return (
      <footer className="py-[100px] text-gray-500">제작 @choiboram</footer>
    );
  const books: BookData[] = await response.json();
  const bookCount = books.length;
  return (
    <footer className="py-[100px] text-gray-500">
      <div>제작 @choiboram</div>
      <div>{bookCount}개의 도서가 등록되어 있습니다.</div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[600px] min-h-screen m-auto px-[15px] bg-white shadow-[0px_7px_29px_0px_rgba(100,_100,_111,_0.2)]">
          <header className="h-[60px] leading-[60px] font-bold text-[18px]">
            <Link href={"/"}>📚 ONEBITE BOOKS</Link>
          </header>
          <main className="pt-[10px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
